### ISSUE TITLE
swagger.apis.default.createOrUpdateStatechartDefinition not a function

### ISSUE THREAD

**Issue by joopringelberg** [JacobeanRnD/smaas-cli#4]
Hello,
after succesfully installing both scxmld and scxml-cli, I find that the cli 'save' command gives this output (on a freshly created statechart file):

joopmac:stateCharts joopringelberg$ scxml save foo.scxml 
/usr/local/lib/node_modules/scxml-cli/client.js:203
          swagger.apis.default.createOrUpdateStatechartDefinition(requestOptio
                               ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/scxml-cli/client.js:203:32
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)

Thanks, 
Joop

**Comment by jbeard4** [comment]
We will investigate and get back to you. Thanks.

**Comment by joopringelberg** [comment]
Installation was completed, but some warnings were issued regarding jquery dependencies:

jquery#2.1.4 public/bower_components/jquery
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires ini@'~1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-git@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'0.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2

On starting scxmld, a message appeared:
joopmac:stateCharts joopringelberg$ scxmld
Missing "WEBSITE_URL" variable.
Db initialized
Starting server on port: 8002
Server started

**Comment by jbeard4** [comment]
Please excuse the delay in my reply. scxmld-0.0.2a published to npm did not peg its git package dependencies to a  particular SHA-1, so they broke over time, as we changed the API. I published a new version of scxmld to npm which fixes this issue. Please try doing a fresh install of scxmld and let me know if the problem persists.

Thank you.

**Comment by joopringelberg** [comment]
Thanks, I installed the new version without any problem. The save command now works and I can run  and interact with a statemachine. However, I cannot visualize it. That is, no errors are thrown upon entering the viz command, but no visualization window opens, either. 
I run on a Mac, 10.7.5. 
In the Console I read a message 'Failed to create CSSymbolicatorRef' and apparently this means that a dynamic library cannot be linked ('the offending executable was compiled against an incompatible SDK').

Re-reading the installation trace I see a lot of NPM unmet dependency warnings (see below). If I interpret the correctly, a lower version is specified than what is installed on my system. I would say that this has nothing to do with linking a dynamic library, though.

Sorry to bother you, but do you have any suggestions how I could proceed?
Thanks.

=================================
jquery#2.1.4 public/bower_components/jquery
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires ini@'~1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-git@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'0.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2

**Comment by jbeard4** [comment]
Not too sure. Could be a bug in atom-shell dependency. 

Try `viz -b`. This should open visualization in a new window of your system's default browser.

**Comment by joopringelberg** [comment]
Thanks. That works perfectly. What a beautiful system!
